### ISSUE TITLE
[pg3] error: addUnManaged: SqliteError: table nodeserver has no column named logLevelList

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc/pg3#47]
Probably the same issue as #45 but initially after installing PG3 I saw these errors

```
7/24/2021, 11:02:38 [pg3] info: [00:21:b9:02:4a:56_9] Unmanaged NodeServer 'Notification' found. Adding to DB.
7/24/2021, 11:02:38 [pg3] info: [00:21:b9:02:4a:56_1] Unmanaged NodeServer 'Airscape' found. Adding to DB.
7/24/2021, 11:02:38 [pg3] info: [00:21:b9:02:4a:56_2] Unmanaged NodeServer 'Camect' found. Adding to DB.
7/24/2021, 10:57:38 [pg3] error: addUnManaged: SqliteError: table nodeserver has no column named logLevelList
    at Database.prepare (<anonymous>)
    at Database.prepare (/var/polyglot/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Object.add (/var/polyglot/node_modules/@universaldevices/pg3/lib/models/nodeserver.js:265:6)
    at addUnManaged (/var/polyglot/node_modules/@universaldevices/pg3/lib/services/nodeservers.js:94:14)
    at /var/polyglot/node_modules/@universaldevices/pg3/lib/services/nodeservers.js:128:19
7/24/2021, 11:02:38 [pg3] error: addUnManaged: SqliteError: table nodeserver has no column named logLevelList
    at Database.prepare (<anonymous>)
    at Database.prepare (/var/polyglot/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Object.add (/var/polyglot/node_modules/@universaldevices/pg3/lib/models/nodeserver.js:265:6)
    at addUnManaged (/var/polyglot/node_modules/@universaldevices/pg3/lib/services/nodeservers.js:94:14)
    at /var/polyglot/node_modules/@universaldevices/pg3/lib/services/nodeservers.js:128:19
7/24/2021, 11:02:38 [pg3] error: addUnManaged: SqliteError: table nodeserver has no column named logLevelList
    at Database.prepare (<anonymous>)
    at Database.prepare (/var/polyglot/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Object.add (/var/polyglot/node_modules/@universaldevices/pg3/lib/models/nodeserver.js:265:6)
    at addUnManaged (/var/polyglot/node_modules/@universaldevices/pg3/lib/services/nodeservers.js:94:14)
    at /var/polyglot/node_modules/@universaldevices/pg3/lib/services/nodeservers.js:128:19
```

**Comment by bpaauwe** [comment]
The PG3 database is out of date.  Deleting the current pg3 database and restarting PG3 will fix the issue.

PG3 has no way to detect an out of date database scheme and auto-update it.  This should be a feature request.
