### ISSUE TITLE
WARNING  interface:send: MQTT Send waiting on connection.

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc/pg3#54]
My nodeserver had an error, then I clicked 'Stop' but polyglot continues to print this warning every 3 seconds.

Version 3.0.20
Status: Connected
Frontend Version: 3.0.19
ISY Version: 5.3.0

```
2021-08-14 12:17:41,819 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:17:42,242 Thread-129 udi_interface      ERROR    udi_interface:write: Exception in thread
2021-08-14 12:17:42,243 Thread-129 udi_interface      ERROR    udi_interface:write: Thread-129
2021-08-14 12:17:42,244 Thread-129 udi_interface      ERROR    udi_interface:write: :
2021-08-14 12:17:42,245 Thread-129 udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2021-08-14 12:17:42,245 Thread-129 udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-08-14 12:17:42,250 Thread-129 udi_interface      ERROR    udi_interface:write: self.run()
2021-08-14 12:17:42,251 Thread-129 udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 870, in run
2021-08-14 12:17:42,255 Thread-129 udi_interface      ERROR    udi_interface:write: self._target(*self._args, **self._kwargs)
2021-08-14 12:17:42,256 Thread-129 udi_interface      ERROR    udi_interface:write: File "/usr/home/admin/dev/pg3/udi-poly-airscape/nodes/Controller.py", line 46, in handler_poll
2021-08-14 12:17:42,258 Thread-129 udi_interface      ERROR    udi_interface:write: self.long_poll()
2021-08-14 12:17:42,259 Thread-129 udi_interface      ERROR    udi_interface:write: File "/usr/home/admin/dev/pg3/udi-poly-airscape/nodes/Controller.py", line 56, in long_poll
2021-08-14 12:17:42,261 Thread-129 udi_interface      ERROR    udi_interface:write: for node in self:
2021-08-14 12:17:42,262 Thread-129 udi_interface      ERROR    udi_interface:write: TypeError
2021-08-14 12:17:42,262 Thread-129 udi_interface      ERROR    udi_interface:write: :
2021-08-14 12:17:42,263 Thread-129 udi_interface      ERROR    udi_interface:write: 'Controller' object is not iterable
2021-08-14 12:17:44,821 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:17:47,828 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:17:50,844 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:17:53,854 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:17:56,882 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:17:59,892 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:18:02,910 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:18:05,957 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:18:08,971 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:18:08,991 Command    udi_interface.interface INFO     interface:_handleInput: Received stop from Polyglot... Shutting Down.
2021-08-14 12:18:08,992 Command    udi_interface.interface INFO     interface:stop: Disconnecting from MQTT... localhost:1888
2021-08-14 12:18:08,993 Command    udi_interface.interface INFO     interface:_disconnect: MQTT Graceful disconnection.
2021-08-14 12:18:08,995 MQTT       udi_interface.interface INFO     interface:_disconnect: MQTT Graceful disconnection.
2021-08-14 12:18:11,995 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:18:15,011 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
```

**Comment by jimboca** [comment]
Actually just noticed this warning always gets printed even before nodeserver stopped?

```
2021-08-14 12:27:51,191 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2021-08-14 12:27:54,017 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:27:55,051 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.0.7 Starting...
2021-08-14 12:27:55,127 MainThread udi_interface.interface INFO     interface:__init__: Connect: Network Interface: {'addr': '192.168.86.86', 'netmask': '255.255.255.0', 'broadcast': '192.168.86.255'}
2021-08-14 12:27:55,130 Interface  udi_interface.interface INFO     interface:_startMqtt: Connecting to MQTT... localhost:1888
2021-08-14 12:27:55,137 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:27:55,248 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Connected with result code 0 (Success)
2021-08-14 12:27:55,250 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Subscribing to topic: udi/pg3/ns/clients/00:21:b9:02:4a:56_25 -  MID: 1 Result: 0
2021-08-14 12:27:55,270 MQTT       udi_interface.interface INFO     interface:_subscribe: MQTT Subscribed Succesfully for Message ID: 1 - QoS: (0,)
2021-08-14 12:27:55,440 MQTT       udi_interface.interface INFO     interface:_message: Successfully set controller :: ST to 1 UOM 2
2021-08-14 12:27:57,020 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:27:58,142 MainThread udi_interface.interface INFO     interface:addNode: Adding node Airscape(controller) [None]
2021-08-14 12:27:58,210 Thread-2   udi_interface      DEBUG    Controller:handler_log_level: level=level
2021-08-14 12:27:58,259 Thread-3   udi_interface      DEBUG    Controller:handler_typed_data: Loading typed data now {params}
2021-08-14 12:27:58,261 Thread-3   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2021-08-14 12:27:58,265 Thread-3   udi_interface      DEBUG    Controller:handler_typed_data: {'airscape2': [{'name': 'name', 'host': 'address'}]}
2021-08-14 12:27:58,262 Thread-4   udi_interface      DEBUG    Controller:handler_typed_params: Loading typed params now {params}
2021-08-14 12:27:58,394 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2021-08-14 12:27:58,436 Thread-6   udi_interface      INFO     Controller:handler_start: Started Airscape NodeServer 2.1.0
2021-08-14 12:27:58,439 Thread-7   udi_interface      DEBUG    Controller:handler_add_node_done: node added {'id': 'b1cf48d1-6317-46aa-bd43-4e085e2600e0', 'uuid': '00:21:b9:02:4a:56', 'profileNum': 25, 'address': 'controller', 'name': 'Airscape', 'nodeDefId': 'controller', 'nls': None, 'hint': '0x00000000', 'controller': 0, 'primaryNode': 'controller', 'private': None, 'isPrimary': 1, 'enabled': 1, 'timeAdded': 1627357708950, 'timeModified': 1627357708950, 'dbVersion': 1}
2021-08-14 12:27:58,440 Thread-6   udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2021-08-14 12:27:58,443 Thread-6   udi_interface      DEBUG    Controller:heartbeat: heartbeat hb=0
2021-08-14 12:27:58,445 Thread-6   udi_interface.custom INFO     custom:_save: Sending data customtypedparams to Polyglot.
2021-08-14 12:27:58,450 Thread-6   udi_interface.interface INFO     interface:addNode: Adding node Airscape name(name) [None]
2021-08-14 12:27:58,586 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = notices
2021-08-14 12:27:58,628 Thread-8   udi_interface      DEBUG    Controller:handler_typed_params: Loading typed params now {params}
2021-08-14 12:27:58,666 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = customtypedparams
2021-08-14 12:27:58,782 Thread-10  udi_interface      DEBUG    Controller:handler_add_node_done: node added {'id': 'a5c1673f-b808-48ad-961e-7fd1508d8453', 'uuid': '00:21:b9:02:4a:56', 'profileNum': 25, 'address': 'name', 'name': 'Airscape name', 'nodeDefId': 'airscape2_F', 'nls': None, 'hint': '0x04110901', 'controller': 0, 'primaryNode': 'controller', 'private': None, 'isPrimary': 0, 'enabled': 1, 'timeAdded': 1627529835588, 'timeModified': 1627529835588, 'dbVersion': 1}
2021-08-14 12:28:00,036 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:03,038 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:06,040 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:09,044 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:12,138 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:18,163 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:21,169 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:24,174 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:27,179 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:30,194 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:33,199 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:36,208 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:39,247 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:42,257 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:45,277 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:48,334 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:51,384 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:54,475 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:28:57,479 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:29:00,484 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:29:03,489 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.
2021-08-14 12:29:06,637 MainThread udi_interface.interface WARNING  interface:send: MQTT Send waiting on connection.

```

**Comment by bpaauwe** [comment]
That warning is reported while waiting for the interface to connect to PG3.  Which is weird because it looks like it did connect and subscribe.

That particular warning is there because the interface can try to send a request to PG3 before the connection is made and needs to wait until the connection is there before actually sending the request.  So it's expected that you may see that message right at the start.

The flag for that is only set and never cleared so once set it should be set until your node server quits.  You're not setting interface.subscribed to false in your node server are you?

**Comment by jimboca** [comment]
I am not setting subscribed, I doubled checked by grepping for it.

**Comment by bpaauwe** [comment]
It shouldn't be possible to get that message if the MQTT connection has started.  From the log, it certainly looks like it has started.

Since you have something that's able to trigger this, can I look at/try what you have so I can figure out what went wrong?

**Comment by jimboca** [comment]
So I was getting nfs working so rebooted the polisy, now I am not seeing it.

**Comment by bpaauwe** [comment]
Well, that's going to make it a bit hard to debug :) But at least it's not a problem now!

Let's keep this issue open for while in case it happens again.

**Comment by jimboca** [comment]
Yes, sorry, will keep it open to see if it shows up again.
